import { Kumbh_Sans } from "next/font/google";
import "./global.css";

import { CartProvider } from "./_context/CartContext";
import { Toaster } from "react-hot-toast";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Sneakers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.className} antialiased mx-auto relative`}>
        <CartProvider>{children}</CartProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
